# Generated by Django 2.2.6 on 2019-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('pubkeyInfo', models.CharField(max_length=256)),
            ],
        ),
    ]
